
### Généralités
caption: 'Simulation'
screen_width: 1600
screen_height: 900
bg_color:  [255, 255, 255]

solution_file_path: 'Test_model/output/solution.txt'
timestep: 0.2
max_time: 250 # à régler dynamiquement !!!!!

interpolate_nodes: False
render_mode: "zones"

### Partie pg_render
# partie vue
view_width: 800
view_height : 800

margin_render: 0.9
nb_elmts_as_max_density: 4
elmt_size: 15
fire_size: 30
nb_fires: 1
fire_threshold: 0.9 # ratioed-loss above which to consider a fire event
# dans la version sully, toujours I=0.5


# Partie pg_toolbar
toolbar_width: 200
toolbar_height: 500
toolbar_margin: 0.1
toolbar_capacity: 10

